Repository intive/patronage22-web-wroclaw, pull requests merged in 2022-04, with the labels that each got.

#64 JI:760835 P2022-649 Dashboard pagination
  libs/shared/src/components/form/form-field/index.tsx
  libs/shared/src/components/form/form-field/render-field.tsx
  libs/shared/src/components/form/form-field/select-field.tsx
  libs/shared/src/components/form/form-field/styled.ts
  libs/shared/src/components/form/index.tsx
  libs/shared/src/components/index.ts
  libs/shared/src/components/layout/index.tsx
  libs/shared/src/components/layout/styled.ts
  libs/shared/src/components/pagination/index.tsx
  libs/shared/src/components/pagination/styled.ts
  libs/shared/src/configs/index.ts
  libs/shared/src/configs/pagination.ts
  libs/shared/src/data/features/feedback/presentation/presentation-slice.ts
  libs/shared/src/types/form-field-type.ts
  libs/shared/src/types/index.ts
  libs/shared/src/types/select-types.ts
  libs/shared/src/utils/index.ts
  libs/translations/src/common/en.json
  libs/translations/src/common/pl.json
  libs/ui/src/stories/basic-layout/index.stories.tsx
  yarn.lock
Labels: enhancement

#61 JI760845 p2022 650 live results view
  libs/features/feedback/src/views/index.ts
  libs/features/feedback/src/views/live-results.tsx
  libs/shared/src/components/diagram/bar-diagram/index.tsx
  libs/shared/src/components/diagram/bar-diagram/styled.ts
  libs/shared/src/components/diagram/get-diagram-config.tsx
  libs/shared/src/components/diagram/index.tsx
  libs/shared/src/components/index.ts
  libs/shared/src/components/timer/index.tsx
  libs/shared/src/components/timer/styled.tsx
  libs/shared/src/configs/diagram-config.ts
  libs/shared/src/configs/index.ts
  libs/shared/src/data/feedback/index.ts
  libs/shared/src/data/feedback/mocks/feedback-result/index.ts
  libs/shared/src/data/feedback/mocks/index.ts
  libs/shared/src/data/feedback/types.ts
  libs/shared/src/types/diagram-type.ts
  libs/shared/src/types/index.ts
  libs/translations/src/common/en.json
  libs/translations/src/common/pl.json
  package-lock.json
  package.json
  yarn.lock
Labels: enhancement

#74 JI773011 P2022 2093 Storybook timer and diagram
  libs/shared/src/components/diagram/index.tsx
  libs/shared/src/components/timer/index.tsx
  libs/ui/src/stories/diagram/diagram.stories.tsx
  libs/ui/src/stories/timer/timer.stories.tsx
Labels: enhancement

#77 JI:773296 P2022-2115 Fix Login page bug
  apps/site/src/app/components/google-login/index.tsx
  apps/site/src/app/components/google-login/styled.ts
  libs/shared/src/constants/regex.ts
  libs/shared/src/data/features/feedback/presentation/presentation-slice.ts
  package.json
  yarn.lock
Labels: bug

#75 JI:768392 P2022-1542 Summary of the finished presentation
  libs/features/feedback/src/components/index.ts
  libs/features/feedback/src/components/presentation-live-summary/index.tsx
  libs/features/feedback/src/components/presentation-live-summary/styled.ts
  libs/shared/src/components/form/form-field/index.tsx
  libs/shared/src/components/form/form-field/render-field.tsx
  libs/shared/src/components/form/index.tsx
  libs/shared/src/data/features/feedback/types.ts
  libs/shared/src/types/form-field-type.ts
  libs/translations/src/feedback/en.json
  libs/translations/src/feedback/pl.json
  libs/ui/src/stories/form/form.stories.tsx
  libs/ui/src/stories/login/login.stories.tsx
  libs/ui/src/stories/presentation-live-summary/presentation-live-summary.stories.tsx
  tsconfig.base.json
Labels: enhancement

#76 JI773438 P2022 2121 Fix-Incorrect font
  apps/site/src/index.html
  libs/shared/src/assets/fonts/licenses/roboto-license
  libs/shared/src/assets/fonts/roboto/roboto-700.eot
  libs/shared/src/assets/fonts/roboto/roboto-700.svg
  libs/shared/src/assets/fonts/roboto/roboto-700.ttf
  libs/shared/src/assets/fonts/roboto/roboto-700.woff
  libs/shared/src/assets/fonts/roboto/roboto-700.woff2
  libs/shared/src/assets/fonts/roboto/roboto-700italic.eot
  libs/shared/src/assets/fonts/roboto/roboto-700italic.svg
  libs/shared/src/assets/fonts/roboto/roboto-700italic.ttf
  libs/shared/src/assets/fonts/roboto/roboto-700italic.woff
  libs/shared/src/assets/fonts/roboto/roboto-700italic.woff2
  libs/shared/src/assets/fonts/roboto/roboto-italic.eot
  libs/shared/src/assets/fonts/roboto/roboto-italic.svg
  libs/shared/src/assets/fonts/roboto/roboto-italic.ttf
  libs/shared/src/assets/fonts/roboto/roboto-italic.woff
  libs/shared/src/assets/fonts/roboto/roboto-italic.woff2
  libs/shared/src/assets/fonts/roboto/roboto-regular.eot
  libs/shared/src/assets/fonts/roboto/roboto-regular.svg
  libs/shared/src/assets/fonts/roboto/roboto-regular.ttf
  libs/shared/src/assets/fonts/roboto/roboto-regular.woff
  libs/shared/src/assets/fonts/roboto/roboto-regular.woff2
  libs/shared/src/styles/index.ts
  libs/shared/src/styles/roboto.ts
  libs/shared/src/utils/get-theme-config.tsx
  yarn.lock
Labels: bug

#82 JI:774238 P2022-2160 Fix share-dialog bug
  apps/site-e2e/tsconfig.json
  apps/site/tsconfig.app.json
  apps/site/tsconfig.spec.json
  libs/features/feedback-e2e/tsconfig.json
  libs/features/feedback/tsconfig.lib.json
  libs/shared/tsconfig.lib.json
  libs/ui/.storybook/tsconfig.json
  libs/ui/tsconfig.lib.json
  tools/globals/typings/qr-code.d.ts
Labels: bug

#81 JI:770151 P2022-1849 [Visual] Spelling error in welcome window on the homepage
  libs/translations/src/feedback/en.json
Labels: bug

#89 JI775194 P2022 2185 fix QRCode component
  package-lock.json
  package.json
  yarn.lock
Labels: bug

#73 JI:773008 P2022-2092 (language selector): fix language detection bug
  libs/shared/src/utils/lang-fns.tsx
  libs/shared/src/utils/load-i18n.ts
Labels: bug

#88 JI:770695 P2022-1907 Add favicon to our site
  apps/site/src/favicon.ico
Labels: enhancement

#87 JI:773039 P2022-2098 [Search] Search bar can be alternately expanded and collapsed on fast tapping below the search bar field
  libs/shared/src/components/search-bar/search-bar.tsx
Labels: bug

#84 JI:773108 P2022-2103 [Visual] Invisible part of the text and moving content when sliding sideways
  apps/site/src/app/pages/not-found/index.tsx
  apps/site/src/app/pages/not-found/styled.ts
  libs/shared/src/components/layout/styled.ts
Labels: bug

#72 JI769773 P2022 1775 Logout component
  apps/site/src/app/components/layout/default-layout/index.tsx
  apps/site/src/app/components/layout/index.tsx
  apps/site/src/app/components/layout/styled.tsx
  libs/features/feedback/src/components/layout/navbar-config.tsx
  libs/shared/src/components/index.ts
  libs/shared/src/components/layout/index.ts
  libs/shared/src/components/layout/layout.tsx
  libs/shared/src/components/layout/styled.ts
  libs/shared/src/components/logout-button/index.tsx
  libs/shared/src/components/logout-button/styled.tsx
  libs/shared/src/components/navbar/index.tsx
  libs/shared/src/components/previous-page-button/index.tsx
  libs/shared/src/components/previous-page-button/styled.ts
  libs/shared/src/types/app-routes.ts
  libs/shared/src/types/protected-routes.ts
  libs/shared/src/utils/index.ts
  libs/shared/src/utils/is-protected-route.ts
  libs/translations/src/common/en.json
  libs/translations/src/common/pl.json
Labels: enhancement

#78 JI:763129 P2022-1049 Login page (part 2)
  .github/workflows/integration.yml
  .github/workflows/preview-deployment.yml
  .github/workflows/prod-deployment.yml
  apps/site/env.sample
  apps/site/src/app/components/auth-gateway/index.tsx
  apps/site/src/app/components/index.ts
  apps/site/src/app/components/login/index.tsx
  apps/site/src/app/components/login/styled.ts
  apps/site/src/app/pages/login/index.tsx
  apps/site/src/app/utils/routing.tsx
  apps/site/src/main.tsx
  libs/shared/project.json
  libs/shared/src/components/form/form-field/index.tsx
  libs/shared/src/components/form/form-field/render-field.tsx
  libs/shared/src/components/form/index.tsx
  libs/shared/src/configs/firebase.ts
  libs/shared/src/configs/index.ts
  libs/shared/src/constants/common.ts
  libs/shared/src/constants/regex.ts
  libs/shared/src/data/site/auth/actions.ts
  libs/shared/src/data/site/auth/auth-slice.ts
  libs/shared/src/data/site/auth/index.ts
  libs/shared/src/data/site/auth/selectors.ts
  libs/shared/src/data/site/index.ts
  libs/shared/src/data/site/mocks/index.ts
  libs/shared/src/data/site/mocks/user-data/index.ts
  libs/shared/src/data/site/types.ts
  libs/shared/src/data/store.ts
  libs/shared/src/environments/environment.prod.ts
  libs/shared/src/environments/environment.ts
  libs/shared/src/hooks/index.ts
  libs/shared/src/hooks/use-clipboard-copy.ts
  libs/shared/src/hooks/use-notification.ts
  libs/shared/src/index.ts
  libs/shared/src/services/firebase/firebase.ts
  libs/shared/src/services/firebase/index.ts
  libs/shared/src/services/firebase/use-firebase-service.ts
  libs/shared/src/services/firebase/use-google-sign-in.ts
  libs/shared/src/services/firebase/use-sign-in-provider.ts
  libs/shared/src/services/index.ts
  libs/shared/src/types/firebase-auth-provider.ts
  libs/shared/src/types/form-field-type.ts
  libs/shared/src/types/http-request-error-name.ts
  libs/shared/src/types/index.ts
  libs/shared/src/utils/index.ts
  libs/shared/src/utils/verify-auth.ts
  libs/translations/src/common/en.json
  libs/translations/src/common/pl.json
  package.json
  tools/globals/typings/qr-code.d.ts
  yarn.lock
Labels: enhancement

#41 JI:759145 P2022-413 Participate in presentation
  README.md
  apps/site/src/app/pages/external-user-presentation/index.tsx
  apps/site/src/i18n.ts
  libs/features/feedback/src/components/presentation-live-summary/index.tsx
  libs/features/feedback/src/components/presentation-live-summary/styled.ts
  libs/features/feedback/src/utils/get-remaining-time.ts
  libs/features/feedback/src/views/current-question-view/get-answer-field.ts
  libs/features/feedback/src/views/current-question-view/index.tsx
  libs/features/feedback/src/views/current-question-view/styled.ts
  libs/features/feedback/src/views/external-presentation-view/index.tsx
  libs/features/feedback/src/views/index.ts
  libs/features/feedback/src/views/live-results/index.tsx
  libs/features/feedback/src/views/live-results/styled.ts
  libs/shared/src/components/form/form-field/radio-group-field.tsx
  libs/shared/src/components/form/form-field/render-field.tsx
  libs/shared/src/components/form/index.tsx
  libs/shared/src/components/timer/index.tsx
  libs/shared/src/components/timer/styled.tsx
  libs/shared/src/data/features/feedback/external-presentation/actions.ts
  libs/shared/src/data/features/feedback/external-presentation/external-presentation-slice.ts
  libs/shared/src/data/features/feedback/external-presentation/index.ts
  libs/shared/src/data/features/feedback/external-presentation/selectors.ts
  libs/shared/src/data/features/feedback/index.ts
  libs/shared/src/data/features/feedback/types.ts
  libs/shared/src/data/feedback/mocks/external-presentation/index.ts
  libs/shared/src/data/feedback/mocks/feedback-result/index.ts
  libs/shared/src/data/feedback/mocks/index.ts
  libs/shared/src/data/feedback/types.ts
  libs/shared/src/data/store.ts
  libs/shared/src/types/form-field-type.ts
  libs/shared/src/types/translations.ts
  libs/shared/src/utils/get-remaining-time.ts
  libs/shared/src/utils/index.ts
  libs/translations/src/common/en.json
  libs/translations/src/common/pl.json
  libs/translations/src/feedback/en.json
  libs/translations/src/feedback/pl.json
  libs/ui/src/stories/presentation-live-summary/presentation-live-summary.stories.tsx
Labels: enhancement

#83 JI769932-P2022-1797-fix-SearchBar
  libs/shared/src/components/search-bar/search-bar.tsx
  libs/shared/src/components/search-bar/search-drawer/index.tsx
  libs/shared/src/components/search-bar/search-input/index.tsx
  libs/shared/src/types/index.ts
  libs/shared/src/types/key-code.ts
  libs/translations/src/common/en.json
  libs/translations/src/common/pl.json
Labels: bug

#90 JI:764431 P2022-1166 Create share and save buttons
  apps/site/src/app/components/login/index.tsx
  apps/site/src/app/components/login/styled.ts
  libs/features/feedback/src/components/basic-presentation-info/index.tsx
  libs/features/feedback/src/components/basic-presentation-info/styled.ts
  libs/features/feedback/src/components/index.ts
  libs/features/feedback/src/components/presentation-live-summary/index.tsx
  libs/features/feedback/src/components/presentation-title-form/index.tsx
  libs/features/feedback/src/components/share-dialog/index.tsx
  libs/features/feedback/src/views/external-presentation-view/index.tsx
  libs/features/feedback/src/views/home/index.tsx
  libs/features/feedback/src/views/new-presentation/index.tsx
  libs/features/feedback/src/views/new-presentation/styled.ts
  libs/translations/src/feedback/en.json
  libs/translations/src/feedback/pl.json
Labels: enhancement

#92 JI:776379 P2022-2192 fix different reloading behaviour in develop preview in task P2022-413
  libs/features/feedback/src/utils/get-remaining-time.ts
  libs/features/feedback/src/views/external-presentation-view/index.tsx
  libs/shared/src/utils/index.ts
  libs/shared/src/utils/is-server-context.ts
Labels: bug

#91 JI:773275 P2022-2114 Clean up readme file
  README.md
  img/answer-closed-screenshot.png
  img/answer-open-screenshot.png
  img/dashboard-screenshot.png
  img/dashboard-share-screenshot.png
  img/homepage-screenshot.png
  img/login-page-screenshot.png
  img/new-presentation-screenshot-2.png
  img/new-presentation-screenshot-3.png
  img/new-presentation-screenshot.png
  img/page-not-found-dark-screenshot.png
  img/page-not-found-pl-screenshot.png
  img/search-screenshot.png
  img/share-presentation-screenshot.png
  img/summary-final-screenshot.png
  img/summary-one-screenshot.png
Labels: documentation

#57 Feature/JI 759143 P2022 412 dashboard
  apps/site/src/app/pages/dashboard/index.tsx
  libs/features/feedback/src/components/dashboard/index.tsx
  libs/features/feedback/src/components/dashboard/styled.ts
  libs/features/feedback/src/components/dashboard/tile/index.tsx
  libs/features/feedback/src/components/dashboard/tile/styled.ts
  libs/features/feedback/src/components/index.ts
  libs/features/feedback/src/types/dashboard.ts
  libs/features/feedback/src/types/index.ts
  libs/shared/src/components/pagination/index.tsx
  libs/shared/src/configs/param-keys.ts
  libs/shared/src/data/feedback/mocks/dashboard/dashboard.json
  libs/shared/src/data/feedback/mocks/dashboard/index.ts
  libs/shared/src/data/feedback/mocks/index.ts
  libs/shared/src/data/feedback/mocks/presentation-search-items/index.ts
  libs/shared/src/types/query-params.ts
  libs/shared/src/utils/get-theme-config.tsx
  libs/translations/src/common/en.json
  libs/translations/src/common/pl.json
  libs/ui/src/stories/dashboard/dashboard.stories.tsx
  libs/ui/src/stories/dashboard/tile.stories.tsx
  libs/ui/src/stories/language-button/language-button.stories.tsx
  package-lock.json
  package.json
  tools/globals/typings/theme.d.ts
  yarn.lock
Labels: enhancement

#93 JI:776422 P2022-2193 Add external-feedback layout
  apps/site/src/app/components/app-name/index.tsx
  apps/site/src/app/components/index.ts
  apps/site/src/app/components/layout/default-layout/index.tsx
  apps/site/src/app/components/layout/index.tsx
  libs/features/feedback/src/components/external-layout/index.tsx
  libs/features/feedback/src/components/index.ts
  libs/features/feedback/src/components/layout/index.ts
  libs/shared/src/components/logout-button/index.tsx
  libs/shared/src/services/firebase/use-firebase-service.ts
Labels: enhancement

#94 JI:776468 P2022-2196 Fix external user layout and logging
  apps/site/src/app/components/layout/default-layout/index.tsx
  libs/shared/src/services/firebase/use-firebase-service.ts
Labels: bug

#101 JI:776572 P2022-2198 fix new question btn
  apps/.gitkeep
  apps/site/project.json
  apps/site/src/environments/environment.prod.ts
  apps/site/src/environments/environment.ts
  apps/site/src/i18n.ts
  docker-compose-dev.yml
  docker-compose-prod.yml
  libs/.gitkeep
  libs/features/feedback/src/assets/.gitkeep
  libs/features/feedback/src/views/new-presentation/styled.ts
  libs/shared/project.json
  libs/shared/src/assets/.gitkeep
  libs/shared/src/environments/environment.prod.ts
  libs/shared/src/environments/environment.ts
  tsconfig.base.json
Labels: bug
